# Generated by Django 4.1.7 on 2023-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
