# Generated by Django 4.1.7 on 2023-03-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_members_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
