# Generated by Django 4.1.7 on 2023-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
