# Generated by Django 4.1.7 on 2023-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
